name: Reusable - Android Emulator Test (Self-Hosted)

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: '17'
      avd_name:
        type: string
        default: 'ciPixel6'
      gpu_mode:
        type: string
        default: 'swiftshader_indirect'
    outputs:
      tests_pass_ratio:
        value: ${{ jobs.emu.outputs.tests_pass_ratio }}
      startup_ms:
        value: ${{ jobs.emu.outputs.startup_ms }}

jobs:
  emu:
    runs-on: self-hosted
    outputs:
      tests_pass_ratio: ${{ steps.ratio.outputs.ratio }}
      startup_ms: ${{ steps.derive.outputs.STARTUP_MS }}
    steps:
      - uses: actions/checkout@v4

      # 1) JDK primero (Gradle lo necesita)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}

      # 2) Bootstrap del wrapper si no existe o está roto
      - name: Bootstrap Gradle wrapper (if missing/broken)
        shell: bash
        run: |
          # Si el wrapper no existe O es sospechoso (muy corto), lo regeneramos
          regen=false
          if [ ! -f gradlew ]; then regen=true; fi
          if [ -f gradlew ] && [ "$(wc -l < gradlew)" -lt 50 ]; then regen=true; fi
          if $regen; then
            echo "Bootstrapping Gradle 8.8..."
            TMP="$RUNNER_TEMP/gradle-boot"; mkdir -p "$TMP"
            curl -fsSL -o "$TMP/gradle.zip" https://services.gradle.org/distributions/gradle-8.8-bin.zip
            unzip -q "$TMP/gradle.zip" -d "$TMP"
            export GRADLE_HOME="$TMP/gradle-8.8"
            export PATH="$GRADLE_HOME/bin:$PATH"
            gradle --version
            gradle wrapper --gradle-version 8.8
          fi

      # 3) Arreglar CRLF y permisos del wrapper
      - name: Ensure Gradle wrapper is executable (and fix CRLF)
        shell: bash
        run: |
          if [ -f gradlew ]; then sed -i 's/\r$//' gradlew; chmod +x gradlew; fi
          find gradle -type f -name "*.properties" -exec sed -i 's/\r$//' {} + 2>/dev/null || true
          # deja el +x en el repo cuando corresponda (no falla si no es repo limpio)
          git update-index --chmod=+x gradlew || true

      # 4) (Opcional) config de cache/telemetría de Gradle
      - uses: gradle/actions/setup-gradle@v3

      # 5) Build unit tests + APK
      - name: Build (unit tests + apk)
        shell: bash
        run: |
          # si tu proyecto está en subcarpeta, añade: cd <ruta>
          ./gradlew --no-daemon clean test assembleDebug

      # 6) Boot del emulador (headless, sin KVM)
      - name: Boot emulator (headless)
        shell: bash
        run: |
          nohup emulator -avd "${{ inputs.avd_name }}" \
            -no-window -no-boot-anim -noaudio -no-snapshot \
            -gpu ${{ inputs.gpu_mode }} -accel off -qemu -m 3072 >/dev/null 2>&1 &
          adb wait-for-device
          for i in {1..120}; do
            b=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            [ "$b" = "1" ] && break
            sleep 2
          done

      # 7) Instrumentation tests
      - name: Instrumentation tests
        shell: bash
        run: ./gradlew --no-daemon connectedDebugAndroidTest

      # 8) Logcat → archivo que lee Promtail (host path mapeado)
      - name: Collect logcat JSON metrics (host path Promtail)
        shell: bash
        run: |
          HOST_LOG_DIR="/home/gha-runner/obs/ci-logs"
          mkdir -p "$HOST_LOG_DIR"
          adb logcat -d | grep METRIC_JSON > "$HOST_LOG_DIR/logcat.jsonl" || true
          mkdir -p ci/logs && cp -f "$HOST_LOG_DIR/logcat.jsonl" ci/logs/logcat.jsonl 2>/dev/null || true

      # 9) Derivar métricas desde el JSON
      - id: derive
        shell: bash
        run: |
          STARTUP=$(jq -r 'select(.metric=="app_startup_ms") | .value' ci/logs/logcat.jsonl 2>/dev/null | head -n1)
          [ -z "$STARTUP" ] && STARTUP=0
          echo "STARTUP_MS=$STARTUP" >> "$GITHUB_OUTPUT"

      - id: ratio
        shell: bash
        run: |
          TOTAL=$(grep -R "<testsuite" app/build/outputs/androidTest-results/connected/* 2>/dev/null | awk -F'"' '{for(i=1;i<=NF;i++){if($i==" tests="){print $(i+1)}}}' | paste -sd+ - | bc || echo 1)
          FAIL=$(grep -R "<testsuite" app/build/outputs/androidTest-results/connected/* 2>/dev/null | awk -F'"' '{for(i=1;i<=NF;i++){if($i==" failures="){print $(i+1)}}}' | paste -sd+ - | bc || echo 0)
          OK=$((TOTAL-FAIL)); export TOTAL OK
          python3 ci/compute_pass_ratio.py > ratio.txt || echo "0" > ratio.txt
          echo "ratio=$(cat ratio.txt)" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: reports-and-logs
          path: |
            app/build/reports
            app/build/outputs/androidTest-results
            ci/logs/logcat.jsonl
