apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: sre-demo
spec:
  replicas: 3
  selector: { matchLabels: { app: api-demo } }
  template:
    metadata: { labels: { app: api-demo } }
    spec:
      containers:
        - name: api
          image: api-demo:local
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - { name: APP_NAME, value: "api-demo" }
            - { name: FAIL_RATE, value: "0.0" }
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo
  namespace: sre-demo
spec:
  selector: { app: api-demo }
  ports:
    - { name: http, port: 80, targetPort: 8080 }
