# Despliegue: SingleBinary (1 pod) y sin componentes extra del modo escalable
deploymentMode: SingleBinary

read:     { replicas: 0 }
write:    { replicas: 0 }
backend:  { replicas: 0 }
chunksCache:   { enabled: false }
resultsCache:  { enabled: false }
gateway:       { enabled: false }
canary:        { enabled: false }
lokiCanary:    { enabled: false }

# ⚠️ USAMOS loki.config PARA BY-PASSEAR EL CALCULATED CONFIG DEL CHART
loki:
  config: |-
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      replication_factor: 1

    # Almacenamiento local (lab)
    storage_config:
      filesystem: {}

    # Esquema boltdb-shipper (lab)
    schema_config:
      configs:
        - from: 2020-10-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    # ⛔ Desactiva structured metadata (requerido con boltdb-shipper en Loki 3.5.x)
    limits_config:
      allow_structured_metadata: false

    # Ruler → Alertmanager del kube-prometheus-stack
    ruler:
      alertmanager_url: http://kube-prometheus-stack-alertmanager.monitoring.svc:9093
      rule_path: /tmp/loki/rules
      ring:
        kvstore:
          store: inmemory
      storage:
        type: local
        local:
          directory: /tmp/loki/rules
      enable_api: true

# Réplica única
singleBinary:
  replicas: 1
  persistence:
    enabled: false
    size: 10Gi
