canary:
  enabled: false

test:
  enabled: false

singleBinary:
  extraVolumeMounts:
    - name: data
      mountPath: /var/loki
  extraVolumes:
    - name: data
      emptyDir: {}


loki:
  # hace pasar la validación del schema de la chart
  useTestSchema: true

  # la chart ahora mira estos nombres aunque uses filesystem
  storage:
    use_thanos_objstore: false
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
      # si la chart pide alguno extra, puedes repetir "loki-<algo>"

  # tu config embebida (sigue igual)
  config: |
    server:
      http_listen_port: 3100

    common:
      replication_factor: 1
      ring:
        kvstore:
          store: memberlist

    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
        - loki-memberlist

    analytics:
      enabled: false
      reporting_enabled: false

    ingester:
      wal:
        enabled: true
        dir: /var/loki/wal

    query_scheduler:
      ring:
        kvstore:
          store: memberlist

    # Almacenamiento local + boltdb-shipper (dev/kind)
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

    # schema explícito (aunque useTestSchema ya desbloquea la validación)
    schema_config:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
