# k8s/loki-values.yaml

deploymentMode: SingleBinary

canary:
  enabled: false

test:
  enabled: false

gateway:
  enabled: false

# 🔹 Solo queremos SingleBinary
singleBinary:
  replicas: 1
  extraVolumeMounts:
    - name: data
      mountPath: /var/loki
  extraVolumes:
    - name: data
      emptyDir: {}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 12
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 12

# 🔻 Desactiva completamente el modo Simple Scalable
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

# (algunas charts también exponen estos alias; por si acaso, a 0)
chunksCache:
  enabled: false
resultsCache:
  enabled: false

loki:
  useTestSchema: true
  storage:
    use_thanos_objstore: false
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin

  config: |
    server:
      http_listen_port: 3100

    common:
      replication_factor: 1
      ring:
        kvstore:
          store: memberlist

    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
        - loki-memberlist

    analytics:
      enabled: false
      reporting_enabled: false

    ingester:
      wal:
        enabled: true
        dir: /var/loki/wal

    query_scheduler:
      ring:
        kvstore:
          store: memberlist

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

    schema_config:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
