# --- modo y componentes ---
deploymentMode: SingleBinary

canary:
  enabled: false

test:
  enabled: false

gateway:
  enabled: false

# --- pod SingleBinary (1 réplica) ---
singleBinary:
  replicas: 1
  # Monta /var/loki efímero (cámbialo a PVC si quieres persistencia real)
  extraVolumeMounts:
    - name: data
      mountPath: /var/loki
  extraVolumes:
    - name: data
      emptyDir: {}
  # Readiness menos agresivo para entornos lentos
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 12
  # Liveness básico
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 12

# --- secciones que la chart valida aunque uses filesystem ---
loki:
  useTestSchema: true
  storage:
    use_thanos_objstore: false
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin

  # Configura Loki (memberlist, filesystem + boltdb-shipper, WAL, etc.)
  config: |
    server:
      http_listen_port: 3100

    common:
      replication_factor: 1
      ring:
        kvstore:
          store: memberlist

    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
        - loki-memberlist

    analytics:
      enabled: false
      reporting_enabled: false

    ingester:
      wal:
        enabled: true
        dir: /var/loki/wal

    query_scheduler:
      ring:
        kvstore:
          store: memberlist

    # Almacenamiento local + boltdb-shipper (ideal para kind/dev)
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

    # Schema explícito
    schema_config:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
