grafana:
  enabled: false

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "default"
      group_by: ["alertname","severity"]
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 1h
      routes:
        - matchers:
            - severity="page"
          receiver: "slack-notify"
    receivers:
      - name: "default"
      - name: "slack-notify"
        slack_configs:
          - send_resolved: true
            channel: "#sre-alerts"
            username: "alertmanager"
            api_url: "${SLACK_WEBHOOK_URL}"
            title: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})"
            text: |
              {{ range .Alerts -}}
              • *{{ .Labels.alertname }}* ({{ .Labels.severity }})
                {{ .Annotations.summary }}
                {{ .Annotations.description }}
              {{ end }}
prometheus:
  enabled: true
