apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo-app
  labels: { app: podinfo }
spec:
  replicas: 2
  selector: { matchLabels: { app: podinfo } }
  template:
    metadata:
      labels: { app: podinfo }
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.4.0
          ports:
            - containerPort: 9898
          readinessProbe:
            httpGet: { path: /readyz, port: 9898 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /livez, port: 9898 }
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: demo-app
  labels: { app: podinfo }
spec:
  selector: { app: podinfo }
  ports:
    - name: http
      port: 80
      targetPort: 9898
      protocol: TCP
