name: Android CI - Build with Fresh Gradle Wrapper

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    # Si tienes runner propio, deja "self-hosted". Si no, usa "ubuntu-latest".
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree (debug)
        run: |
          pwd
          ls -la

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Force fresh Gradle wrapper (8.8) + fix CRLF/permissions
        shell: bash
        run: |
          # Estamos en la raíz del proyecto (donde vive settings.gradle(.kts))
          if [ ! -f settings.gradle ] && [ ! -f settings.gradle.kts ]; then
            echo "❌ No se encontró settings.gradle(.kts) en $PWD"
            exit 1
          fi

          # Elimina wrapper roto si existe
          rm -f   gradlew gradlew.bat || true
          rm -rf  gradle/wrapper      || true

          # Descarga Gradle "portátil" para generar wrapper
          TMP="$RUNNER_TEMP/gradle-boot"; rm -rf "$TMP"; mkdir -p "$TMP"
          curl -fsSL -o "$TMP/gradle.zip" https://services.gradle.org/distributions/gradle-8.8-bin.zip
          unzip -q "$TMP/gradle.zip" -d "$TMP"
          export GRADLE_HOME="$TMP/gradle-8.8"
          export PATH="$GRADLE_HOME/bin:$PATH"

          # Verifica gradle y genera wrapper en el repo
          gradle --version
          gradle wrapper --gradle-version 8.8

          # Normaliza fin de línea (por si el repo vino con CRLF) y da permisos
          sed -i 's/\r$//' gradlew || true
          chmod +x gradlew

          echo "Wrapper generado:"
          ls -la gradlew gradlew.bat gradle/wrapper

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Ensure AndroidX flags in gradle.properties
        shell: bash
        run: |
          FILE="gradle.properties"
          touch "$FILE"
          sed -i '/^android.useAndroidX=/d' "$FILE" || true
          sed -i '/^android.enableJetifier=/d' "$FILE" || true
          {
            echo "android.useAndroidX=true"
            echo "android.enableJetifier=true"
          } >> "$FILE"
          echo "==== gradle.properties ===="
          cat "$FILE"

      - name: Build (unit tests + apk)
        shell: bash
        run: |
          ./gradlew --no-daemon clean test assembleDebug

      # (Opcional) Sube artefactos
      - name: Upload APK and reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: |
            app/build/outputs
            app/build/reports
