name: Android CI E2E (Cloud)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PUSHGATEWAY_URL: ${{ secrets.PUSHGATEWAY_URL }}
  GRAFANA_URL:     ${{ secrets.GRAFANA_URL }}

jobs:
  tests:
    uses: ./.github/workflows/reusable_android_emulator_test.yml

  publish:
    needs: tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Publish to observability
        uses: ./.github/actions/observability-publish
        with:
          pushgateway_url:  ${{ env.PUSHGATEWAY_URL }}
          grafana_url:      ${{ env.GRAFANA_URL }}
          startup_ms:       ${{ needs.tests.outputs.startup_ms }}
          pass_ratio:       ${{ needs.tests.outputs.tests_pass_ratio }}
          missed_frames:    0
          login_ok:         5
          login_fail:       0
          grafana_api_key:  ${{ secrets.GRAFANA_API_KEY }}

  quality_gates:
    needs: [tests, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Enforce SLOs
        shell: bash
        run: |
          STARTUP="${{ needs.tests.outputs.startup_ms || 0 }}"
          RATIO="${{ needs.tests.outputs.tests_pass_ratio || 0 }}"
          echo "Startup: ${STARTUP} ms | Pass ratio: ${RATIO}"
          if [ "$STARTUP" -gt 2500 ]; then echo "❌ Startup > 2500ms"; exit 1; fi
          awk -v r="$RATIO" 'BEGIN{ if (r+0 < 0.9) { print "❌ Pass ratio < 0.9"; exit 1 } }'
          echo "✅ Quality gates OK"
